"""add dashboard soft delete

Revision ID: 6b7a78fbdec9
Revises: f25e16a44003
Create Date: 2026-10-01 12:44:51.482596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6b7a78fbdec9'
down_revision: Union[str, None] = 'f25e16a44003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboards', sa.Column('deleted_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True))
    op.create_index(op.f('ix_dashboards_deleted_at'), 'dashboards', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dashboards_deleted_at'), table_name='dashboards')
    op.drop_column('dashboards', 'deleted_at')
    # ### end Alembic commands ###
