"""initial schema

Revision ID: f25e16a44003
Revises: 
Create Date: 2026-10-01 12:01:04.355974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f25e16a44003'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('layout_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plugins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('installed_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sensors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('ingest_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('threshold_min', sa.Float(), nullable=True),
    sa.Column('threshold_max', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('deleted_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_sensors_deleted_at'), 'sensors', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_sensors_ingest_key'), 'sensors', ['ingest_key'], unique=True)
    op.create_table('alarms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('triggered_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('resolved_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('acknowledged_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('acknowledged_by', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', name='alarmstatus'), nullable=False),
    sa.Column('threshold_breached', sa.Enum('MIN', 'MAX', name='thresholdbreached'), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarms_sensor_id'), 'alarms', ['sensor_id'], unique=False)
    op.create_table('plugin_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plugin_id', sa.Uuid(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugin_configs_plugin_id'), 'plugin_configs', ['plugin_id'], unique=False)
    op.create_table('readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('recorded_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reading_sensor_recorded', 'readings', ['sensor_id', 'recorded_at'], unique=False)
    op.create_table('widgets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('grid_column', sa.Integer(), nullable=False),
    sa.Column('grid_row', sa.Integer(), nullable=False),
    sa.Column('grid_width', sa.Integer(), nullable=False),
    sa.Column('grid_height', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_widgets_dashboard_id'), 'widgets', ['dashboard_id'], unique=False)
    op.create_table('widget_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('widget_id', sa.Uuid(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['widget_id'], ['widgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_widget_configs_widget_id'), 'widget_configs', ['widget_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_widget_configs_widget_id'), table_name='widget_configs')
    op.drop_table('widget_configs')
    op.drop_index(op.f('ix_widgets_dashboard_id'), table_name='widgets')
    op.drop_table('widgets')
    op.drop_index('ix_reading_sensor_recorded', table_name='readings')
    op.drop_table('readings')
    op.drop_index(op.f('ix_plugin_configs_plugin_id'), table_name='plugin_configs')
    op.drop_table('plugin_configs')
    op.drop_index(op.f('ix_alarms_sensor_id'), table_name='alarms')
    op.drop_table('alarms')
    op.drop_index(op.f('ix_sensors_ingest_key'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_deleted_at'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_table('plugins')
    op.drop_table('dashboards')
    # ### end Alembic commands ###
